# Generated by Django 4.2.7 on 2024-06-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_fact_service_skill_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='title',
            field=models.CharField(choices=[('about', 'about'), ('facts', 'facts'), ('skills', 'skills'), ('services', 'services'), ('resume', 'resume'), ('portfolio', 'portfolio'), ('contact', 'contact'), ('testimonial', 'testimonial')], max_length=220),
        ),
    ]
