# Generated by Django 4.2.7 on 2024-06-22 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_category', models.CharField(max_length=100)),
                ('portfolio_name', models.CharField(max_length=100)),
                ('portfolio_image', models.ImageField(upload_to='portfolio_images/')),
                ('portfolio_url', models.CharField(default=1, max_length=233)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_heading', models.CharField(max_length=255)),
                ('portfolio_client', models.CharField(max_length=100)),
                ('portfolio_project_date', models.DateField()),
                ('portfolio_project_url', models.URLField()),
                ('portfolio_title', models.CharField(max_length=255)),
                ('portfolio_description', models.TextField()),
                ('portfolio_image_1', models.ImageField(upload_to='portfolio_images/details/')),
                ('portfolio_image_2', models.ImageField(upload_to='portfolio_images/details/')),
                ('portfolio_image_3', models.ImageField(upload_to='portfolio_images/details/')),
                ('keywords', models.TextField(default='dhruvwebfolio')),
                ('description', models.TextField(default='dhruv')),
                ('date', models.DateField(auto_now_add=True)),
                ('portfolio_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PortFolio.portfolio', verbose_name='Portfolilo')),
            ],
        ),
    ]
