# Generated by Django 4.2.7 on 2024-06-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortFolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_image',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='portfoliodetails',
            name='portfolio_image_1',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='portfoliodetails',
            name='portfolio_image_2',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='portfoliodetails',
            name='portfolio_image_3',
            field=models.CharField(max_length=220),
        ),
    ]
